dataset:
  train: dataset/brazil/grounding_dino_labels/train.json
  val: dataset/brazil/grounding_dino_labels/val.json
  test: dataset/brazil/grounding_dino_labels/test.json
  image_root: dataset/brazil/dataset_yolo_auto_labeling/images

model:
  pretrained_model: GroundingDINO/weights/groundingdino_swint_ogc.pth  # à télécharger plus bas
  use_caption_prompt: False
  caption_prompt: "school"

train:
  batch_size: 32
  lr: 1e-4
  weight_decay: 0.05
  epochs: 30
  output_dir: results/brazil/groundingdino_brazil
  save_every: 5
